packette_stream: FIXED iterator non-sense with packetteRun() object ADDED Sorted list of event numbers and accessor method (no more grabbing the offsetTable) ADDED reporting on numbers of new events and time to index
packette_browse:
FIXED double-print on refresh()
FIXED incorrect usage of packetteRun() object, which caused all events to be loaded into memory ::clown::
ADDED alpha to graphing of multiple events, so you can get a quick sense of what's going on

Probably some other things too.

packette_calibration:
FIXED more iterator non-sense

diff --git a/pedestal_it b/pedestal_it
--- a/pedestal_it
+++ b/pedestal_it
@@ -30,8 +30,13 @@ fi
 echo "Requesting unmodified waveforms..."
 time ./A2x_tool.py -I -c 0xffffffffffffffff --zsuppress 0 --pedestal 0 -r $rate -t $threads -a $baseport -N "$2" "$3"
 
-echo "Sleeping..."
-sleep 1
+if [ "$?" -ne "0" ]; then
+    echo "Waveform request has failed.  Killing packette."
+    kill -2 -$pid
+fi
+
+#echo "Sleeping..."
+#sleep 1
 
 echo "Verifying that packette is still running (meaning we got data)..."
     
